name: e_shop
description: Flutter eCommerce App using Firebase Firestore from Coding Cafe

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.3.0
  numberpicker: ^2.1.1
  firebase_auth: ^2.0.0
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  image_picker: ^0.8.1+3
  flutter_rating_bar: ^4.0.0
  firebase_storage: ^9.0.0
  firebase_core: ^1.3.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  flutter_swiper: ^1.1.2
  rubber: ^1.0.0
  flutter_svg: ^0.22.0
  sizer: ^2.0.13
  google_sign_in: ^5.0.4
  google_maps_flutter: ^2.0.6
  geolocator: ^7.2.0+1
  geocoder: ^0.2.1
  flutter_facebook_auth: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf
  

  assets:
  - assets/
  - assets/icons/



